### ISSUE TITLE
The slides are broken

### ISSUE THREAD

**Issue by marcofiset** [shaunlebron/t3tr0s-slides#3]
I get this error when loading the page : `Invalid match arg: /^[.#]/`

**Comment by shaunlebron** [comment]
Thanks for reporting.  I looked into it tonight without getting far.  I can't get a meaningful stack trace, and upgrading the dependencies didn't help.

I'm bewildered at how this could break when all the dependencies were bundled.  Browser behavior must've shifted.

**Comment by marco-fiset** [comment]
After investigating that more by myself, I found that this error is seemingly thrown from here https://github.com/clojure/clojurescript/blob/master/src/main/cljs/clojure/string.cljs#L55

Not sure if it is of any help, but thought I might share.

**Comment by shaunlebron** [comment]
Slides should be fixed now:
http://shaunlebron.github.io/t3tr0s-slides

I never figured out what happened; just ported the slides to use Rum instead of an old version of Om.

Thanks again for reporting 👍
